# Generated by Django 5.1.6 on 2025-05-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(default='NORMAL_POST', max_length=200),
        ),
    ]
