# Generated by Django 5.1.6 on 2025-04-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnifund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
